services:
  ######################################################
  # R Testing
  ######################################################
  r-test:
    image: r-package/tidylab
    build:
      context: ./
      dockerfile: ./.dev/docker/r-test/Dockerfile
    entrypoint: '/bin/bash'
    container_name: r_test
    restart: "no"
  ######################################################
  # R for Package Development
  ######################################################
  r-package:
    image: tidylab/package:4.1.1
    build:
      context: ./
      dockerfile: ./inst/docker/r-package/Dockerfile
    entrypoint: '/bin/bash'
    restart: "no"
  ######################################################
  # R for Project Development
  ######################################################
  r-project:
    image: tidylab/project:4.1.1
    build:
      context: ./
      dockerfile: ./inst/docker/r-project/Dockerfile
    entrypoint: '/bin/bash'
    restart: "no"
    depends_on:
      - "r-package"
  ######################################################
  # R for Machine Learning
  ######################################################
  r-ml:
    image: tidylab/ml:4.1.1
    build:
      context: ./
      dockerfile: ./inst/docker/r-ml/Dockerfile
    entrypoint: '/bin/bash'
    restart: "no"
    depends_on:
      - "r-package"
  ######################################################
  # R for Books
  ######################################################
  r-book:
    image: tidylab/book:4.1.1
    build:
      context: ./
      dockerfile: ./inst/docker/r-book/Dockerfile
    entrypoint: '/bin/bash'
    restart: "no"
    depends_on:
      - "r-package"
  ######################################################
  # R for Microservices
  ######################################################
  r-microservice:
    image: tidylab/microservice:4.1.1
    build:
      context: ./
      dockerfile: ./inst/docker/r-microservice/Dockerfile
    entrypoint: '/bin/bash'
    restart: "no"
    depends_on:
      - "r-package"
  ######################################################
  # R for Stan <https://mc-stan.org/>
  ######################################################
  r-stanverse:
    image: tidylab/stanverse:4.1.1
    build:
      context: ./
      dockerfile: ./inst/docker/r-stanverse/Dockerfile
    entrypoint: '/bin/bash'
    restart: "no"
    depends_on:
      - "r-package"
  ######################################################
version: "3.3"
networks:
  default:
    name: tidylab
