# R Package Project: Core ------------------------------------------------------
FROM tidylab/package:4.0.5

# Additional Packages ----------------------------------------------------------
RUN R -q -e "install_cran(c('janitor'), dependencies = TRUE)"
