# R Package Development: Project -----------------------------------------------
FROM tidylab/package:4.1.1

# Additional Packages ----------------------------------------------------------
RUN R -q -e "install_cran(c('janitor'), dependencies = TRUE)"
